/**
 * Builds what the skill ships beside its sources, so that the skill folder is the whole package an
 * agent or a bot downloads, and needs nothing from this repository:
 *
 *   lib/bound-verify.mjs       the agent's verifier (src/verify.ts, with @bound/verifier and friends)
 *   bin/bound-verify.mjs       the command for bots in other languages (src/cli.ts and the example)
 *   reference/AGENT-API.md     the API reference, copied from AGENT-API.md
 *
 * Only @solana/kit stays external, since the agent installs it anyway (the skill's package.json).
 *
 *   node tools/build-skill.ts           write them
 *   node tools/build-skill.ts --check   fail if a committed file differs from a fresh build (CI)
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { rolldown } from 'rolldown';

const SKILL = 'skills/bound-protected-swap';

async function bundle(input: string, banner: string): Promise<string> {
  const b = await rolldown({
    input,
    external: id => id === '@solana/kit' || id.startsWith('@solana/kit/'),
    platform: 'node',
    logLevel: 'warn',
  });
  const { output } = await b.generate({ format: 'esm', banner });
  await b.close();
  return output[0].code;
}

const outputs: [path: string, content: string][] = [
  [`${SKILL}/lib/bound-verify.mjs`, await bundle(
    `${SKILL}/src/verify.ts`,
    '// Generated by tools/build-skill.ts from skills/bound-protected-swap/src/verify.ts and @bound/verifier. Do not edit.',
  )],
  [`${SKILL}/bin/bound-verify.mjs`, await bundle(
    `${SKILL}/src/cli-entry.ts`,
    '#!/usr/bin/env node\n// Generated by tools/build-skill.ts from skills/bound-protected-swap/src/cli.ts and examples/swap.ts. Do not edit.',
  )],
  [`${SKILL}/reference/AGENT-API.md`,
    `<!-- Copied from AGENT-API.md by tools/build-skill.ts. Edit that file, not this one. -->\n\n${readFileSync('AGENT-API.md', 'utf8').replace(/\r\n/g, '\n')}`],
];

const lf = (s: string) => s.replace(/\r\n/g, '\n');
if (process.argv.includes('--check')) {
  let stale = 0;
  for (const [path, content] of outputs) {
    let committed = '';
    try {
      committed = readFileSync(path, 'utf8');
    } catch {
      // missing
    }
    if (lf(committed) !== lf(content)) {
      console.error(`${path} differs from a fresh build. Run: node tools/build-skill.ts`);
      stale++;
    } else console.log(`${path} matches its source`);
  }
  if (stale) process.exit(1);
} else {
  for (const [path, content] of outputs) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`${path}: ${content.length} bytes`);
  }
}
