/**
 * Builds what the skill ships beside its sources, so that the skill folder is the whole package an
 * agent or a bot downloads, and needs nothing from this repository:
 *
 *   lib/bound-verify.mjs       the agent's verifier (src/verify.ts, with @bound/verifier and friends)
 *   bin/bound-verify.mjs       the command for bots in other languages (src/cli.ts and the example)
 *   reference/AGENT-API.md     the API reference, copied from AGENT-API.md
 *   SHA256SUMS                 the hash of every file the skill ships (`sha256sum -c SHA256SUMS`)
 *
 * and, for the site, apps/web/lib/server/skillSums.ts: the same hashes, served at /skill/SHA256SUMS,
 * so that a copy of the skill can be checked against a second channel (final audit, item 10).
 *
 * Only @solana/kit stays external, pinned to one version with a lockfile of hashes (package.json,
 * package-lock.json). Hashes are of the files with LF line ends, which .gitattributes keeps on
 * every checkout.
 *
 *   node tools/build-skill.ts           write them
 *   node tools/build-skill.ts --check   fail if a committed file differs from a fresh build (CI)
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { rolldown } from 'rolldown';

const SKILL = 'skills/bound-protected-swap';
/** What the skill ships, besides SHA256SUMS itself, in the order the sums list them. */
const SHIPPED = [
  'SKILL.md', 'README.md', 'package.json', 'package-lock.json', 'examples/swap.ts', 'lib/bound-verify.mjs',
  'lib/bound-verify.d.mts', 'bin/bound-verify.mjs', 'src/verify.ts', 'src/cli.ts', 'src/cli-entry.ts', 'reference/AGENT-API.md',
];

async function bundle(input: string, banner: string): Promise<string> {
  const b = await rolldown({
    input,
    external: id => id === '@solana/kit' || id.startsWith('@solana/kit/'),
    platform: 'node',
    logLevel: 'warn',
  });
  const { output } = await b.generate({ format: 'esm', banner });
  await b.close();
  return output[0].code;
}

const lf = (s: string) => s.replace(/\r\n/g, '\n');
const sums = () => SHIPPED.map(file =>
  `${createHash('sha256').update(lf(readFileSync(`${SKILL}/${file}`, 'utf8'))).digest('hex')}  ${file}`).join('\n') + '\n';
const skillVersion = () => (JSON.parse(readFileSync(`${SKILL}/package.json`, 'utf8')) as { version: string }).version;

// In order, each written before the next is built: the command bundles the example, which imports
// lib/bound-verify.mjs from disk, so the verifier must be current before the command is bundled, and
// the sums are taken of the files as they are once everything before them is written.
const outputs: [path: string, make: () => Promise<string>][] = [
  [`${SKILL}/lib/bound-verify.mjs`, () => bundle(
    `${SKILL}/src/verify.ts`,
    '// Generated by tools/build-skill.ts from skills/bound-protected-swap/src/verify.ts and @bound/verifier. Do not edit.',
  )],
  [`${SKILL}/bin/bound-verify.mjs`, () => bundle(
    `${SKILL}/src/cli-entry.ts`,
    '#!/usr/bin/env node\n// Generated by tools/build-skill.ts from skills/bound-protected-swap/src/cli.ts and examples/swap.ts. Do not edit.',
  )],
  [`${SKILL}/reference/AGENT-API.md`, async () =>
    `<!-- Copied from AGENT-API.md by tools/build-skill.ts. Edit that file, not this one. -->\n\n${lf(readFileSync('AGENT-API.md', 'utf8'))}`],
  [`${SKILL}/SHA256SUMS`, async () => sums()],
  ['apps/web/lib/server/skillSums.ts', async () => [
    '// Generated by tools/build-skill.ts: the hashes of the skill Bound distributes, served at /skill/SHA256SUMS. Do not edit.',
    `export const SKILL_VERSION = '${skillVersion()}';`,
    `export const SKILL_SUMS = ${JSON.stringify(sums())};`,
    '',
  ].join('\n')],
];

const check = process.argv.includes('--check');
let stale = 0;
for (const [path, make] of outputs) {
  const content = await make();
  if (check) {
    let committed = '';
    try {
      committed = readFileSync(path, 'utf8');
    } catch {
      // missing
    }
    if (lf(committed) !== lf(content)) {
      console.error(`${path} differs from a fresh build. Run: node tools/build-skill.ts`);
      stale++;
    } else console.log(`${path} matches its source`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`${path}: ${content.length} bytes`);
  }
}
if (stale) process.exit(1);
