/**
 * Bundles the agent's verifier (skills/bound-protected-swap/src/verify.ts, which imports
 * @bound/verifier and friends) into one file the skill ships: lib/bound-verify.mjs. Only
 * @solana/kit stays external, since the agent installs it anyway.
 *
 *   node tools/build-skill.ts           write the bundle
 *   node tools/build-skill.ts --check   fail if the committed bundle differs from a fresh build (CI)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { rolldown } from 'rolldown';

const SKILL = 'skills/bound-protected-swap';
const OUT = `${SKILL}/lib/bound-verify.mjs`;

const bundle = await rolldown({
  input: `${SKILL}/src/verify.ts`,
  external: id => id === '@solana/kit' || id.startsWith('@solana/kit/'),
  platform: 'node',
  logLevel: 'warn',
});
const { output } = await bundle.generate({
  format: 'esm',
  banner: '// Generated by tools/build-skill.ts from skills/bound-protected-swap/src/verify.ts and @bound/verifier. Do not edit.',
});
await bundle.close();
const code = output[0].code;

if (process.argv.includes('--check')) {
  let committed = '';
  try {
    committed = readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    // missing
  }
  if (committed !== code.replace(/\r\n/g, '\n')) {
    console.error(`${OUT} differs from a fresh build of the verifier. Run: node tools/build-skill.ts`);
    process.exit(1);
  }
  console.log(`${OUT} matches the verifier`);
} else {
  writeFileSync(OUT, code);
  console.log(`${OUT}: ${code.length} bytes`);
}
